apiVersion: v1
kind: ServiceAccount
metadata:
  name: deis3
---
apiVersion: v1
kind: Pod
metadata:
  name: deis3
  labels:
    app: deis3
spec:
  serviceAccount: deis3
  containers:
  - name: deis3
    image: quay.io/bacongobbler/deis3:canary
    imagePullPolicy: Always
    ports:
    - containerPort: 2222
      hostPort: 2222
      name: gitreceive
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
  - name: registry
    image: registry:2
    imagePullPolicy: Always
    ports:
    - containerPort: 5000
      hostPort: 5000
      name: registry
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: deis3
spec:
  ports:
    - name: http
      port: 22
      targetPort: 2222
    - name: registry
      port: 80
      targetPort: 5000
  selector:
    app: deis3
