apiVersion: v1
kind: Pod
metadata:
  name: deis3
spec:
  containers:
  - name: deis3
    image: quay.io/bacongobbler/deis3:canary
    ports:
    - containerPort: 2222
      name: gitreceive
  - name: registry
    image: registry:2.3.1
    ports:
    - containerPort: 5000
      name: registry
---
apiVersion: v1
kind: Service
metadata:
  name: deis3
  labels:
    heritage: deis
spec:
  ports:
    - name: http
      port: 22
      targetPort: 2222
    - name: registry
      port: 80
      targetPort: 5000
  selector:
    app: deis3
