apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    heritage: codebuilder
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: {{ .Values.name }}
