name: codebuilder
home: https://github.com/bacongobbler/codebuilder
version: v0.1.0
description: Chart shim for apps that do not provide a chart.
maintainers:
  - name: Deis Team
    email: engineering@deis.com
